class TranslateModel {
    constructor() {
        this.dictionary = {
            "some": "якийсь, просто",
            "test": "тест, тестування",
            "for": "для",
            "translation": "перекладу",
            "ebbing": "згасало",
            "light": "світлий",
            "yellow": "жовтий",
            "straight": "прямо",
            "mocking": "глузливий",
            "tense": "напружений",
            "broken": "розбитий",
            "metal": "металевий",
            "particular": "особливий",
            "wind-browned": "вітром обвітрений",
            "cynical": "цинічний",
            "intelligent": "розумний",
            "immense": "величезний",
            "diffused": "розсіяний",
            "conscientious": "сумлінний",
            "old": "старий",
            "random": "випадковий",
            "probably": "ймовірно",
            "lousy": "паршивий",
            "occupied": "зайнятий",
            "crap": "лайно",
            "bores": "нудить",
            "hemorrhages": "крововиливи",
            "touchy": "образливий",
            "apiece": "по одному",
            "hell": "пекло",
            "madman": "божевільний",
            "run-down": "виснажений",
            "crumby": "жалюгідний",
            "practically": "практично",
            "drive": "їхати",
            "around": "навколо",
            "regular": "звичайний",
            "terrific": "чудовий",
            "anybody": "хтось",
            "goldfish": "золота рибка",
            "prostitute": "проститутка",
            "mention": "згадувати",
            "advertise": "рекламувати",
            "hotshot": "крутий (розмовне)",
            "polo": "поло",
            "splendid": "блискучий",
            "clear-thinking": "ясномислячий",
            "big": "великий",
            "deal": "справа"
            "broken": "розбитий",
            "clouds": "хмари",
            "coffee": "кава",
            "color": "колір",
            "conscientious": "сумлінний",
            "crack": "тріщина",
            "cup": "чашка",
            "cynical": "цинічний",
            "days": "дні",
            "desire": "бажання",
            "despair": "відчай",
            "details": "деталі",
            "diffused": "розсіяний",
            "dime": "монетка (10 центів)",
            "doorway": "дверний прохід",
            "dread": "страх",
            "explanations": "пояснення",
            "expression": "вираз",
            "eyes": "очі",
            "face": "обличчя",
            "fading": "вицвілий",
            "feeling": "почуття",
            "glass": "скло",
            "glints": "відблиски",
            "glow": "сяйво",
            "grime": "бруд",
            "hastily": "поспішно",
            "immense": "величезний",
            "intelligent": "розумний",
            "interest": "інтерес",
            "intervals": "інтервали",
            "jagged": "зубчастий",
            "leaf": "лист",
            "length": "довжина",
            "light": "світло",
            "lightning": "блискавка",
            "lines": "лінії",
            "masterpiece": "шедевр",
            "metal": "металевий",
            "mocking": "глузливий",
            "moment": "момент",
            "motionless": "нерухомий",
            "object": "об'єкт",
            "often": "часто",
            "oil": "олія (живопис)",
            "old": "старий",
            "painting": "картина",
            "particular": "особливий",
            "pinnacles": "вежі",
            "problem": "проблема",
            "question": "питання",
            "reason": "причина",
            "red": "червоний",
            "resignation": "покора",
            "roofs": "дахи",
            "self-discipline": "самодисципліна",
            "sense": "відчуття",
            "shadow": "тінь",
            "shafts": "промені",
            "shape": "форма",
            "shoulders": "плечі",
            "side": "бік",
            "simply": "просто",
            "sky": "небо",
            "skyscrapers": "хмарочоси",
            "slender": "стрункий",
            "soot-eaten": "закопчений",
            "source": "джерело",
            "spire": "шпиль",
            "still": "нерухомо",
            "stories": "історії / поверхи (контекстно)",
            "streaks": "смуги",
            "street": "вулиця",
            "streets": "вулиці",
            "suddenly": "раптово",
            "sunset": "захід сонця",
            "tense": "напружений",
            "things": "речі",
            "tower": "вежа",
            "twilight": "сутінки",
            "uneasiness": "тривога",
            "voice": "голос",
            "walls": "стіни",
            "weariness": "втома",
            "wedge": "клин",
            "wind-browned": "обвітрений",
            "yellow": "жовтий"
            "art": "мистецтво",
            "artist": "художник",
            "beauty": "краса",
            "bees": "бджоли",
            "birds": "птахи",
            "blossoms": "квіти",
            "branches": "гілки",
            "burden": "тягар",
            "centre": "центр",
            "cigarettes": "сигарети",
            "conjectures": "здогадки",
            "corner": "кут",
            "curtains": "штори",
            "delicate": "ніжний",
            "dim": "тьмяний",
            "disappearance": "зникнення",
            "distant": "віддалений",
            "divan": "диван",
            "door": "двері",
            "dusty": "пиловий",
            "easel": "мольберт",
            "effect": "ефект",
            "excitement": "збудження",
            "extraordinary": "надзвичайний",
            "fantastic": "фантастичний",
            "flamelike": "вогняний",
            "flight": "політ",
            "full-length": "на повний зріст",
            "garden": "сад",
            "gleam": "блиск",
            "grass": "трава",
            "hardly": "ледь",
            "heavy": "важкий",
            "honey-coloured": "медового кольору",
            "honey-sweet": "солодкий, як мед",
            "horns": "роги",
            "huge": "величезний",
            "immobile": "нерухомий",
            "jade-faced": "з обличчям, як нефрит",
            "laburnum": "золотий дощ (дерево)",
            "light": "світлий / світло",
            "lilac": "бузок",
            "london": "Лондон",
            "long": "довгий",
            "man": "чоловік",
            "momentary": "миттєвий",
            "monotonous": "монотонний",
            "motion": "рух",
            "murmur": "бурмотіння / гул",
            "necessarily": "неминуче",
            "note": "нота",
            "odour": "запах",
            "open": "відчинений",
            "organ": "орган (музичний)",
            "painters": "художники",
            "pallid": "блідий",
            "perfume": "аромат",
            "personal": "особистий",
            "pink-flowering": "рожевоквітучий",
            "portrait": "портрет",
            "public": "публічний",
            "rich": "насичений / багатий",
            "roar": "рев",
            "room": "кімната",
            "roses": "троянди",
            "saddle-bags": "сідельні сумки",
            "scent": "аромат",
            "sense": "відчуття",
            "shadows": "тіні",
            "stillness": "нерухомість",
            "straggling": "розкиданий",
            "strange": "дивний",
            "studio": "майстерня",
            "sudden": "раптовий",
            "sullen": "похмурий",
            "summer": "літній",
            "swiftness": "швидкість",
            "thorn": "терен",
            "time": "час",
            "tokyo": "Токіо",
            "trees": "дерева",
            "tremulous": "тремтливий",
            "upright": "вертикальний",
            "wind": "вітер",
            "window": "вікно",
            "woodbine": "жимолость",
            "years": "роки",
            "young": "молодий"
            "failed": "провалив",
            "maybe": "можливо",
            "won't": "не будуть",
            "happened": "сталося",
            "secretary": "секретар",
            "a lot": "багато",
            "little": "маленький",
            "only": "тільки",
            "chairs": "стілець",
            "white": "білий",
            "spilled": "розлитий",
            "said": "сказав",
            "comfortable": "зручно",
            "relax": "розслабитися",
            "doctor": "лікар",
            "didn't": "не",
            "open": "відкрити",
            "forgot": "забув",
            "remember": "пам’ятати",
            "tight": "міцно",
            "ain't": "не є",
            "scared": "наляканий",
            "hurt": "боляче",
            "rabbit's": "кролячий",
            "pocket": "кишеня",
            "too": "також"

    };
    }

    translate(word) {
        return this.dictionary[word.toLowerCase().replace(/[.,!?;:]/g, "")] || null;
    }
}